name: Bedrock
version: '${project.version}'
main: me.jasper1229.bedrock.Bedrock
api-version: 1.13
authors: [ Jasper1229 ]
description: This plugin provides basic commands that are the bedrock of all of your servers!
commands:
  btp:
    permission: bedrock.teleport
  frog:
    permission: bedrock.frog
  find:
    permission: bedrock.find
<<<<<<< HEAD
  dnp:
    permission: bedrock.dnp
    aliases: [disablenetherportals,dnportals]
=======
>>>>>>> e632c1df66738824a1b11c22598a8cfff6b75acc
